# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alicat_control_ui.ui'
#
# Created: Mon May 20 18:33:06 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(1015, 680)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(650, 10, 351, 361))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.lcd_mean_velocity = QtGui.QLCDNumber(self.tab)
        self.lcd_mean_velocity.setGeometry(QtCore.QRect(150, 30, 101, 41))
        self.lcd_mean_velocity.setObjectName(_fromUtf8("lcd_mean_velocity"))
        self.lcd_power = QtGui.QLCDNumber(self.tab)
        self.lcd_power.setGeometry(QtCore.QRect(150, 80, 101, 41))
        self.lcd_power.setObjectName(_fromUtf8("lcd_power"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(20, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(50, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_43 = QtGui.QLabel(self.tab)
        self.label_43.setGeometry(QtCore.QRect(257, 40, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_45 = QtGui.QLabel(self.tab)
        self.label_45.setGeometry(QtCore.QRect(260, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_burnerGeom = QtGui.QWidget()
        self.tab_burnerGeom.setObjectName(_fromUtf8("tab_burnerGeom"))
        self.radio_button_burnerHoles = QtGui.QRadioButton(self.tab_burnerGeom)
        self.radio_button_burnerHoles.setGeometry(QtCore.QRect(40, 70, 82, 17))
        self.radio_button_burnerHoles.setChecked(True)
        self.radio_button_burnerHoles.setObjectName(_fromUtf8("radio_button_burnerHoles"))
        self.radio_button_burnerSlits = QtGui.QRadioButton(self.tab_burnerGeom)
        self.radio_button_burnerSlits.setGeometry(QtCore.QRect(40, 100, 82, 17))
        self.radio_button_burnerSlits.setObjectName(_fromUtf8("radio_button_burnerSlits"))
        self.input_burnerDim_a = QtGui.QLineEdit(self.tab_burnerGeom)
        self.input_burnerDim_a.setGeometry(QtCore.QRect(210, 70, 51, 20))
        self.input_burnerDim_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_burnerDim_a.setObjectName(_fromUtf8("input_burnerDim_a"))
        self.input_burnerDim_b = QtGui.QLineEdit(self.tab_burnerGeom)
        self.input_burnerDim_b.setGeometry(QtCore.QRect(210, 100, 51, 20))
        self.input_burnerDim_b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_burnerDim_b.setObjectName(_fromUtf8("input_burnerDim_b"))
        self.input_burnerDim_no = QtGui.QLineEdit(self.tab_burnerGeom)
        self.input_burnerDim_no.setGeometry(QtCore.QRect(210, 130, 51, 20))
        self.input_burnerDim_no.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_burnerDim_no.setObjectName(_fromUtf8("input_burnerDim_no"))
        self.label_5 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_5.setGeometry(QtCore.QRect(180, 70, 21, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_6.setGeometry(QtCore.QRect(180, 100, 21, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_20 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_20.setGeometry(QtCore.QRect(110, 130, 91, 21))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_21.setGeometry(QtCore.QRect(270, 70, 21, 21))
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_22.setGeometry(QtCore.QRect(270, 100, 21, 21))
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.tabWidget.addTab(self.tab_burnerGeom, _fromUtf8(""))
        self.tab_gas = QtGui.QWidget()
        self.tab_gas.setObjectName(_fromUtf8("tab_gas"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_gas)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 10, 291, 201))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(80, 20, 46, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_29 = QtGui.QLabel(self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(30, 140, 71, 21))
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.groupBox_3)
        self.label_30.setGeometry(QtCore.QRect(60, 110, 41, 21))
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.lineEdit_fuel_SCP = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_fuel_SCP.setGeometry(QtCore.QRect(112, 80, 91, 20))
        self.lineEdit_fuel_SCP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_fuel_SCP.setObjectName(_fromUtf8("lineEdit_fuel_SCP"))
        self.lineEdit_fuel_A_F = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_fuel_A_F.setGeometry(QtCore.QRect(112, 50, 91, 20))
        self.lineEdit_fuel_A_F.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_fuel_A_F.setObjectName(_fromUtf8("lineEdit_fuel_A_F"))
        self.lineEdit_fuel_viscosity = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_fuel_viscosity.setGeometry(QtCore.QRect(112, 140, 91, 20))
        self.lineEdit_fuel_viscosity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_fuel_viscosity.setObjectName(_fromUtf8("lineEdit_fuel_viscosity"))
        self.label_28 = QtGui.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(210, 80, 46, 21))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.lineEdit_fuel_density = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_fuel_density.setGeometry(QtCore.QRect(112, 110, 91, 20))
        self.lineEdit_fuel_density.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_fuel_density.setObjectName(_fromUtf8("lineEdit_fuel_density"))
        self.label_27 = QtGui.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(80, 80, 21, 21))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_26 = QtGui.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(80, 50, 21, 21))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_31 = QtGui.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(210, 110, 81, 21))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.lineEdit_fuel_molweight = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_fuel_molweight.setGeometry(QtCore.QRect(112, 170, 91, 20))
        self.lineEdit_fuel_molweight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_fuel_molweight.setObjectName(_fromUtf8("lineEdit_fuel_molweight"))
        self.label_35 = QtGui.QLabel(self.groupBox_3)
        self.label_35.setGeometry(QtCore.QRect(10, 170, 91, 21))
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_39 = QtGui.QLabel(self.groupBox_3)
        self.label_39.setGeometry(QtCore.QRect(210, 140, 71, 21))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_41 = QtGui.QLabel(self.groupBox_3)
        self.label_41.setGeometry(QtCore.QRect(210, 170, 46, 21))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.comboBox_fuel = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_fuel.setGeometry(QtCore.QRect(110, 20, 91, 22))
        self.comboBox_fuel.setObjectName(_fromUtf8("comboBox_fuel"))
        self.comboBox_fuel.addItem(_fromUtf8(""))
        self.comboBox_fuel.addItem(_fromUtf8(""))
        self.lineEdit_fuel_gas_ID = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_fuel_gas_ID.setGeometry(QtCore.QRect(240, 20, 31, 20))
        self.lineEdit_fuel_gas_ID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_fuel_gas_ID.setObjectName(_fromUtf8("lineEdit_fuel_gas_ID"))
        self.label_46 = QtGui.QLabel(self.groupBox_3)
        self.label_46.setGeometry(QtCore.QRect(210, 20, 21, 21))
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_gas)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 220, 291, 111))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_32 = QtGui.QLabel(self.groupBox_4)
        self.label_32.setGeometry(QtCore.QRect(30, 50, 71, 21))
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(60, 20, 41, 21))
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.lineEdit_air_viscosity = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_air_viscosity.setGeometry(QtCore.QRect(112, 50, 91, 20))
        self.lineEdit_air_viscosity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_air_viscosity.setObjectName(_fromUtf8("lineEdit_air_viscosity"))
        self.lineEdit_air_density = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_air_density.setGeometry(QtCore.QRect(112, 20, 91, 20))
        self.lineEdit_air_density.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_air_density.setObjectName(_fromUtf8("lineEdit_air_density"))
        self.label_34 = QtGui.QLabel(self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(210, 20, 71, 21))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.lineEdit_air_molweight = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_air_molweight.setGeometry(QtCore.QRect(110, 80, 91, 20))
        self.lineEdit_air_molweight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_air_molweight.setObjectName(_fromUtf8("lineEdit_air_molweight"))
        self.label_37 = QtGui.QLabel(self.groupBox_4)
        self.label_37.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.groupBox_4)
        self.label_38.setGeometry(QtCore.QRect(210, 50, 81, 21))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_40 = QtGui.QLabel(self.groupBox_4)
        self.label_40.setGeometry(QtCore.QRect(210, 80, 46, 21))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.tabWidget.addTab(self.tab_gas, _fromUtf8(""))
        self.tab_connection = QtGui.QWidget()
        self.tab_connection.setObjectName(_fromUtf8("tab_connection"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_connection)
        self.groupBox_5.setGeometry(QtCore.QRect(60, 110, 201, 81))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.input_fuelControllerID = QtGui.QLineEdit(self.groupBox_5)
        self.input_fuelControllerID.setGeometry(QtCore.QRect(30, 20, 61, 20))
        self.input_fuelControllerID.setObjectName(_fromUtf8("input_fuelControllerID"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.input_fuelControllerMaxCapac = QtGui.QLineEdit(self.groupBox_5)
        self.input_fuelControllerMaxCapac.setGeometry(QtCore.QRect(90, 50, 61, 20))
        self.input_fuelControllerMaxCapac.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_fuelControllerMaxCapac.setObjectName(_fromUtf8("input_fuelControllerMaxCapac"))
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(160, 50, 51, 21))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_9 = QtGui.QLabel(self.tab_connection)
        self.label_9.setGeometry(QtCore.QRect(50, 30, 51, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_connection)
        self.groupBox_6.setGeometry(QtCore.QRect(60, 200, 201, 81))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.input_airControllerID = QtGui.QLineEdit(self.groupBox_6)
        self.input_airControllerID.setGeometry(QtCore.QRect(30, 20, 61, 20))
        self.input_airControllerID.setObjectName(_fromUtf8("input_airControllerID"))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.input_airControllerMaxCapac = QtGui.QLineEdit(self.groupBox_6)
        self.input_airControllerMaxCapac.setGeometry(QtCore.QRect(90, 50, 61, 20))
        self.input_airControllerMaxCapac.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_airControllerMaxCapac.setObjectName(_fromUtf8("input_airControllerMaxCapac"))
        self.label_23 = QtGui.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(160, 50, 51, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.input_connection_port = QtGui.QLineEdit(self.tab_connection)
        self.input_connection_port.setGeometry(QtCore.QRect(120, 30, 113, 20))
        self.input_connection_port.setObjectName(_fromUtf8("input_connection_port"))
        self.tabWidget.addTab(self.tab_connection, _fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 220, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.dial_flowRate_Air_incr = QtGui.QDial(self.centralwidget)
        self.dial_flowRate_Air_incr.setEnabled(False)
        self.dial_flowRate_Air_incr.setGeometry(QtCore.QRect(350, 80, 51, 71))
        self.dial_flowRate_Air_incr.setPageStep(1)
        self.dial_flowRate_Air_incr.setTracking(True)
        self.dial_flowRate_Air_incr.setObjectName(_fromUtf8("dial_flowRate_Air_incr"))
        self.Button_flowrate_Fuel_down = QtGui.QPushButton(self.centralwidget)
        self.Button_flowrate_Fuel_down.setEnabled(False)
        self.Button_flowrate_Fuel_down.setGeometry(QtCore.QRect(260, 290, 71, 31))
        self.Button_flowrate_Fuel_down.setObjectName(_fromUtf8("Button_flowrate_Fuel_down"))
        self.Button_flowrate_Fuel_up = QtGui.QPushButton(self.centralwidget)
        self.Button_flowrate_Fuel_up.setEnabled(False)
        self.Button_flowrate_Fuel_up.setGeometry(QtCore.QRect(260, 210, 71, 31))
        self.Button_flowrate_Fuel_up.setObjectName(_fromUtf8("Button_flowrate_Fuel_up"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 80, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_flowRate_A_mode = QtGui.QLabel(self.centralwidget)
        self.label_flowRate_A_mode.setGeometry(QtCore.QRect(5, 110, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_flowRate_A_mode.setFont(font)
        self.label_flowRate_A_mode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_flowRate_A_mode.setWordWrap(True)
        self.label_flowRate_A_mode.setObjectName(_fromUtf8("label_flowRate_A_mode"))
        self.lcd_temperature_Air = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_temperature_Air.setGeometry(QtCore.QRect(210, 370, 81, 41))
        self.lcd_temperature_Air.setAutoFillBackground(False)
        self.lcd_temperature_Air.setSmallDecimalPoint(False)
        self.lcd_temperature_Air.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_temperature_Air.setObjectName(_fromUtf8("lcd_temperature_Air"))
        self.dial_flowRate_Fuel_incr = QtGui.QDial(self.centralwidget)
        self.dial_flowRate_Fuel_incr.setEnabled(False)
        self.dial_flowRate_Fuel_incr.setGeometry(QtCore.QRect(350, 220, 51, 71))
        self.dial_flowRate_Fuel_incr.setMaximum(100)
        self.dial_flowRate_Fuel_incr.setSingleStep(1)
        self.dial_flowRate_Fuel_incr.setPageStep(1)
        self.dial_flowRate_Fuel_incr.setOrientation(QtCore.Qt.Horizontal)
        self.dial_flowRate_Fuel_incr.setInvertedAppearance(False)
        self.dial_flowRate_Fuel_incr.setObjectName(_fromUtf8("dial_flowRate_Fuel_incr"))
        self.button_abort = QtGui.QPushButton(self.centralwidget)
        self.button_abort.setEnabled(False)
        self.button_abort.setGeometry(QtCore.QRect(540, 270, 75, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.button_abort.setPalette(palette)
        self.button_abort.setObjectName(_fromUtf8("button_abort"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 340, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.button_reset = QtGui.QPushButton(self.centralwidget)
        self.button_reset.setEnabled(False)
        self.button_reset.setGeometry(QtCore.QRect(540, 370, 75, 41))
        self.button_reset.setObjectName(_fromUtf8("button_reset"))
        self.lcd_pressure_Air = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_pressure_Air.setGeometry(QtCore.QRect(90, 370, 81, 41))
        self.lcd_pressure_Air.setAutoFillBackground(False)
        self.lcd_pressure_Air.setSmallDecimalPoint(False)
        self.lcd_pressure_Air.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_pressure_Air.setObjectName(_fromUtf8("lcd_pressure_Air"))
        self.lcd_flowrate_Fuel = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_flowrate_Fuel.setGeometry(QtCore.QRect(130, 250, 121, 61))
        self.lcd_flowrate_Fuel.setFrameShape(QtGui.QFrame.Box)
        self.lcd_flowrate_Fuel.setFrameShadow(QtGui.QFrame.Raised)
        self.lcd_flowrate_Fuel.setSmallDecimalPoint(False)
        self.lcd_flowrate_Fuel.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_flowrate_Fuel.setObjectName(_fromUtf8("lcd_flowrate_Fuel"))
        self.Button_flowrate_Air_down = QtGui.QPushButton(self.centralwidget)
        self.Button_flowrate_Air_down.setEnabled(False)
        self.Button_flowrate_Air_down.setGeometry(QtCore.QRect(260, 150, 71, 31))
        self.Button_flowrate_Air_down.setObjectName(_fromUtf8("Button_flowrate_Air_down"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(390, 330, 141, 81))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.ignition_massflow_set_point = QtGui.QLineEdit(self.groupBox)
        self.ignition_massflow_set_point.setGeometry(QtCore.QRect(80, 20, 51, 20))
        self.ignition_massflow_set_point.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ignition_massflow_set_point.setObjectName(_fromUtf8("ignition_massflow_set_point"))
        self.ignition_phi_set_point = QtGui.QLineEdit(self.groupBox)
        self.ignition_phi_set_point.setGeometry(QtCore.QRect(80, 50, 51, 20))
        self.ignition_phi_set_point.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ignition_phi_set_point.setObjectName(_fromUtf8("ignition_phi_set_point"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(15, 20, 61, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 46, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 340, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_flowRate_B_mode = QtGui.QLabel(self.centralwidget)
        self.label_flowRate_B_mode.setGeometry(QtCore.QRect(5, 250, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_flowRate_B_mode.setFont(font)
        self.label_flowRate_B_mode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_flowRate_B_mode.setWordWrap(True)
        self.label_flowRate_B_mode.setObjectName(_fromUtf8("label_flowRate_B_mode"))
        self.Button_flowrate_Air_up = QtGui.QPushButton(self.centralwidget)
        self.Button_flowrate_Air_up.setEnabled(False)
        self.Button_flowrate_Air_up.setGeometry(QtCore.QRect(260, 70, 71, 31))
        self.Button_flowrate_Air_up.setObjectName(_fromUtf8("Button_flowrate_Air_up"))
        self.lcd_flowrate_Air = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_flowrate_Air.setGeometry(QtCore.QRect(130, 110, 121, 61))
        self.lcd_flowrate_Air.setFrameShape(QtGui.QFrame.Box)
        self.lcd_flowrate_Air.setFrameShadow(QtGui.QFrame.Raised)
        self.lcd_flowrate_Air.setSmallDecimalPoint(False)
        self.lcd_flowrate_Air.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_flowrate_Air.setObjectName(_fromUtf8("lcd_flowrate_Air"))
        self.button_ignition = QtGui.QPushButton(self.centralwidget)
        self.button_ignition.setEnabled(False)
        self.button_ignition.setGeometry(QtCore.QRect(540, 320, 75, 41))
        self.button_ignition.setDefault(False)
        self.button_ignition.setFlat(False)
        self.button_ignition.setObjectName(_fromUtf8("button_ignition"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(250, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(250, 110, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lcd_flowRate_setPoint_Air = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_flowRate_setPoint_Air.setGeometry(QtCore.QRect(190, 70, 61, 31))
        self.lcd_flowRate_setPoint_Air.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_flowRate_setPoint_Air.setObjectName(_fromUtf8("lcd_flowRate_setPoint_Air"))
        self.lcd_flowRate_setPoint_Fuel = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_flowRate_setPoint_Fuel.setGeometry(QtCore.QRect(190, 210, 61, 31))
        self.lcd_flowRate_setPoint_Fuel.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_flowRate_setPoint_Fuel.setObjectName(_fromUtf8("lcd_flowRate_setPoint_Fuel"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 10, 221, 201))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.button_record_set = QtGui.QPushButton(self.groupBox_2)
        self.button_record_set.setEnabled(False)
        self.button_record_set.setGeometry(QtCore.QRect(130, 160, 75, 23))
        self.button_record_set.setObjectName(_fromUtf8("button_record_set"))
        self.comments_textBox = QtGui.QTextEdit(self.groupBox_2)
        self.comments_textBox.setGeometry(QtCore.QRect(30, 40, 171, 111))
        self.comments_textBox.setObjectName(_fromUtf8("comments_textBox"))
        self.label_36 = QtGui.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(30, 20, 91, 20))
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.button_new_record_set = QtGui.QPushButton(self.groupBox_2)
        self.button_new_record_set.setGeometry(QtCore.QRect(30, 160, 91, 23))
        self.button_new_record_set.setObjectName(_fromUtf8("button_new_record_set"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(100, 69, 81, 31))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(110, 209, 71, 31))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.flowrate_Air_incr = QtGui.QDoubleSpinBox(self.centralwidget)
        self.flowrate_Air_incr.setGeometry(QtCore.QRect(281, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.flowrate_Air_incr.setFont(font)
        self.flowrate_Air_incr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.flowrate_Air_incr.setDecimals(2)
        self.flowrate_Air_incr.setSingleStep(0.1)
        self.flowrate_Air_incr.setProperty("value", 0.1)
        self.flowrate_Air_incr.setObjectName(_fromUtf8("flowrate_Air_incr"))
        self.flowrate_Fuel_incr = QtGui.QDoubleSpinBox(self.centralwidget)
        self.flowrate_Fuel_incr.setGeometry(QtCore.QRect(281, 250, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.flowrate_Fuel_incr.setFont(font)
        self.flowrate_Fuel_incr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.flowrate_Fuel_incr.setDecimals(2)
        self.flowrate_Fuel_incr.setSingleStep(0.1)
        self.flowrate_Fuel_incr.setProperty("value", 0.1)
        self.flowrate_Fuel_incr.setObjectName(_fromUtf8("flowrate_Fuel_incr"))
        self.progressBar_fuel_meter_scale = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_fuel_meter_scale.setGeometry(QtCore.QRect(130, 310, 121, 16))
        self.progressBar_fuel_meter_scale.setProperty("value", 0)
        self.progressBar_fuel_meter_scale.setTextVisible(False)
        self.progressBar_fuel_meter_scale.setObjectName(_fromUtf8("progressBar_fuel_meter_scale"))
        self.progressBar_air_meter_scale = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_air_meter_scale.setGeometry(QtCore.QRect(130, 170, 121, 16))
        self.progressBar_air_meter_scale.setProperty("value", 0)
        self.progressBar_air_meter_scale.setTextVisible(False)
        self.progressBar_air_meter_scale.setObjectName(_fromUtf8("progressBar_air_meter_scale"))
        self.record_list = QtGui.QTreeWidget(self.centralwidget)
        self.record_list.setGeometry(QtCore.QRect(10, 430, 991, 191))
        self.record_list.setObjectName(_fromUtf8("record_list"))
        self.pushButton_clear_records = QtGui.QPushButton(self.centralwidget)
        self.pushButton_clear_records.setGeometry(QtCore.QRect(900, 630, 101, 23))
        self.pushButton_clear_records.setObjectName(_fromUtf8("pushButton_clear_records"))
        self.pushButton_save_button = QtGui.QPushButton(self.centralwidget)
        self.pushButton_save_button.setGeometry(QtCore.QRect(810, 630, 81, 23))
        self.pushButton_save_button.setObjectName(_fromUtf8("pushButton_save_button"))
        self.delete_record_button = QtGui.QPushButton(self.centralwidget)
        self.delete_record_button.setGeometry(QtCore.QRect(30, 630, 81, 23))
        self.delete_record_button.setObjectName(_fromUtf8("delete_record_button"))
        self.pushButton_start = QtGui.QPushButton(self.centralwidget)
        self.pushButton_start.setEnabled(False)
        self.pushButton_start.setGeometry(QtCore.QRect(540, 220, 75, 41))
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.button_openCloseSerial = QtGui.QPushButton(self.centralwidget)
        self.button_openCloseSerial.setEnabled(False)
        self.button_openCloseSerial.setGeometry(QtCore.QRect(710, 380, 121, 23))
        self.button_openCloseSerial.setObjectName(_fromUtf8("button_openCloseSerial"))
        self.pushButton_apply_all_settings = QtGui.QPushButton(self.centralwidget)
        self.pushButton_apply_all_settings.setGeometry(QtCore.QRect(840, 380, 151, 23))
        self.pushButton_apply_all_settings.setObjectName(_fromUtf8("pushButton_apply_all_settings"))
        self.groupBox_7 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(60, 10, 301, 51))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.radioButton_air_fuel_SLPM = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_air_fuel_SLPM.setGeometry(QtCore.QRect(20, 20, 91, 17))
        self.radioButton_air_fuel_SLPM.setCheckable(True)
        self.radioButton_air_fuel_SLPM.setChecked(True)
        self.radioButton_air_fuel_SLPM.setObjectName(_fromUtf8("radioButton_air_fuel_SLPM"))
        self.buttonGroup = QtGui.QButtonGroup(mainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton_air_fuel_SLPM)
        self.radioButton_massflow = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_massflow.setGeometry(QtCore.QRect(200, 20, 91, 17))
        self.radioButton_massflow.setObjectName(_fromUtf8("radioButton_massflow"))
        self.buttonGroup.addButton(self.radioButton_massflow)
        self.radioButton_re_phi = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_re_phi.setGeometry(QtCore.QRect(120, 20, 82, 17))
        self.radioButton_re_phi.setChecked(False)
        self.radioButton_re_phi.setAutoExclusive(True)
        self.radioButton_re_phi.setObjectName(_fromUtf8("radioButton_re_phi"))
        self.buttonGroup.addButton(self.radioButton_re_phi)
        self.label_42 = QtGui.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(350, 130, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setWordWrap(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_44 = QtGui.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(350, 270, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setWordWrap(True)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Alicat Control", None))
        self.label_16.setText(_translate("mainWindow", "Mean Velocity", None))
        self.label_17.setText(_translate("mainWindow", "Power", None))
        self.label_43.setText(_translate("mainWindow", "m/s", None))
        self.label_45.setText(_translate("mainWindow", "W", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Page", None))
        self.radio_button_burnerHoles.setText(_translate("mainWindow", "Holes", None))
        self.radio_button_burnerSlits.setText(_translate("mainWindow", "Slits", None))
        self.input_burnerDim_a.setText(_translate("mainWindow", "0.0015", None))
        self.input_burnerDim_b.setText(_translate("mainWindow", "0.001", None))
        self.input_burnerDim_no.setText(_translate("mainWindow", "19", None))
        self.label_5.setText(_translate("mainWindow", "a", None))
        self.label_6.setText(_translate("mainWindow", "b", None))
        self.label_20.setText(_translate("mainWindow", "# of holes/slits", None))
        self.label_21.setText(_translate("mainWindow", "m", None))
        self.label_22.setText(_translate("mainWindow", "m", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_burnerGeom), _translate("mainWindow", "Burner Geometry", None))
        self.groupBox_3.setTitle(_translate("mainWindow", "Fuel Settings", None))
        self.label_25.setText(_translate("mainWindow", "Fuel", None))
        self.label_29.setText(_translate("mainWindow", "din. viscosity", None))
        self.label_30.setText(_translate("mainWindow", "density", None))
        self.lineEdit_fuel_SCP.setText(_translate("mainWindow", "50.36", None))
        self.lineEdit_fuel_SCP.setPlaceholderText(_translate("mainWindow", "0", None))
        self.lineEdit_fuel_A_F.setText(_translate("mainWindow", "17.195", None))
        self.lineEdit_fuel_A_F.setPlaceholderText(_translate("mainWindow", "0", None))
        self.lineEdit_fuel_viscosity.setText(_translate("mainWindow", "1.0997e-5", None))
        self.lineEdit_fuel_viscosity.setPlaceholderText(_translate("mainWindow", "0", None))
        self.label_28.setText(_translate("mainWindow", "MJ/Kg", None))
        self.lineEdit_fuel_density.setText(_translate("mainWindow", "0.6569", None))
        self.lineEdit_fuel_density.setPlaceholderText(_translate("mainWindow", "0", None))
        self.label_27.setText(_translate("mainWindow", "SCP", None))
        self.label_26.setText(_translate("mainWindow", "A/F", None))
        self.label_31.setText(_translate("mainWindow", "Kg/m3  @ 25ºC", None))
        self.lineEdit_fuel_molweight.setText(_translate("mainWindow", "16.044", None))
        self.lineEdit_fuel_molweight.setPlaceholderText(_translate("mainWindow", "0", None))
        self.label_35.setText(_translate("mainWindow", "molecular weight", None))
        self.label_39.setText(_translate("mainWindow", "Kg/ms  @ 25ºC", None))
        self.label_41.setText(_translate("mainWindow", "Kg/Kmol", None))
        self.comboBox_fuel.setItemText(0, _translate("mainWindow", "CH4", None))
        self.comboBox_fuel.setItemText(1, _translate("mainWindow", "C3H8", None))
        self.lineEdit_fuel_gas_ID.setText(_translate("mainWindow", "2", None))
        self.label_46.setText(_translate("mainWindow", "ID", None))
        self.groupBox_4.setTitle(_translate("mainWindow", "Air Settings", None))
        self.label_32.setText(_translate("mainWindow", "din. viscosity", None))
        self.label_33.setText(_translate("mainWindow", "density", None))
        self.lineEdit_air_viscosity.setText(_translate("mainWindow", "1.965e-5", None))
        self.lineEdit_air_viscosity.setPlaceholderText(_translate("mainWindow", "0", None))
        self.lineEdit_air_density.setText(_translate("mainWindow", "1.184", None))
        self.lineEdit_air_density.setPlaceholderText(_translate("mainWindow", "0", None))
        self.label_34.setText(_translate("mainWindow", "Kg/m3 @ 25ºC", None))
        self.lineEdit_air_molweight.setText(_translate("mainWindow", "28.97", None))
        self.lineEdit_air_molweight.setPlaceholderText(_translate("mainWindow", "0", None))
        self.label_37.setText(_translate("mainWindow", "molecular weight", None))
        self.label_38.setText(_translate("mainWindow", "Kg/ms  @ 25ºC", None))
        self.label_40.setText(_translate("mainWindow", "Kg/Kmol", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gas), _translate("mainWindow", "Fuel/Air Mixture Settings", None))
        self.groupBox_5.setTitle(_translate("mainWindow", "Fuel controller", None))
        self.input_fuelControllerID.setText(_translate("mainWindow", "A", None))
        self.label_10.setText(_translate("mainWindow", "ID", None))
        self.label_11.setText(_translate("mainWindow", "Max. capacity", None))
        self.input_fuelControllerMaxCapac.setText(_translate("mainWindow", "5", None))
        self.label_24.setText(_translate("mainWindow", "SLPM", None))
        self.label_9.setText(_translate("mainWindow", "Serial Port", None))
        self.groupBox_6.setTitle(_translate("mainWindow", "Air controller", None))
        self.input_airControllerID.setText(_translate("mainWindow", "B", None))
        self.label_12.setText(_translate("mainWindow", "ID", None))
        self.label_13.setText(_translate("mainWindow", "Max. capacity", None))
        self.input_airControllerMaxCapac.setText(_translate("mainWindow", "20", None))
        self.label_23.setText(_translate("mainWindow", "SLPM", None))
        self.input_connection_port.setText(_translate("mainWindow", "COM4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_connection), _translate("mainWindow", "Connection Settings", None))
        self.label_8.setText(_translate("mainWindow", "Fuel", None))
        self.Button_flowrate_Fuel_down.setText(_translate("mainWindow", "Down", None))
        self.Button_flowrate_Fuel_up.setText(_translate("mainWindow", "Up", None))
        self.label_7.setText(_translate("mainWindow", "Air", None))
        self.label_flowRate_A_mode.setText(_translate("mainWindow", "air SLPM", None))
        self.button_abort.setText(_translate("mainWindow", "Abort", None))
        self.label_2.setText(_translate("mainWindow", "Temp", None))
        self.button_reset.setText(_translate("mainWindow", "Reset", None))
        self.Button_flowrate_Air_down.setText(_translate("mainWindow", "Down", None))
        self.groupBox.setTitle(_translate("mainWindow", "Ignition set point", None))
        self.ignition_massflow_set_point.setText(_translate("mainWindow", "5", None))
        self.ignition_phi_set_point.setText(_translate("mainWindow", "1", None))
        self.label_3.setText(_translate("mainWindow", "total SLPM", None))
        self.label_4.setText(_translate("mainWindow", "phi", None))
        self.label.setText(_translate("mainWindow", "PSIA", None))
        self.label_flowRate_B_mode.setText(_translate("mainWindow", "fuel SLPM", None))
        self.Button_flowrate_Air_up.setText(_translate("mainWindow", "Up", None))
        self.button_ignition.setText(_translate("mainWindow", "Ignition", None))
        self.label_14.setText(_translate("mainWindow", "incr.", None))
        self.label_15.setText(_translate("mainWindow", "incr.", None))
        self.groupBox_2.setTitle(_translate("mainWindow", "Records", None))
        self.button_record_set.setText(_translate("mainWindow", "record point", None))
        self.label_36.setText(_translate("mainWindow", "Comments", None))
        self.button_new_record_set.setText(_translate("mainWindow", "new record set", None))
        self.label_18.setText(_translate("mainWindow", "SLPM set point", None))
        self.label_19.setText(_translate("mainWindow", "SLPM set point", None))
        self.record_list.headerItem().setText(0, _translate("mainWindow", "Record #", None))
        self.record_list.headerItem().setText(1, _translate("mainWindow", "Record set", None))
        self.record_list.headerItem().setText(2, _translate("mainWindow", "Re", None))
        self.record_list.headerItem().setText(3, _translate("mainWindow", "phi", None))
        self.record_list.headerItem().setText(4, _translate("mainWindow", "TotalSLPM", None))
        self.record_list.headerItem().setText(5, _translate("mainWindow", "AirSLPM", None))
        self.record_list.headerItem().setText(6, _translate("mainWindow", "FuelSLPM", None))
        self.record_list.headerItem().setText(7, _translate("mainWindow", "Power", None))
        self.record_list.headerItem().setText(8, _translate("mainWindow", "U_mean", None))
        self.record_list.headerItem().setText(9, _translate("mainWindow", "Pressure", None))
        self.record_list.headerItem().setText(10, _translate("mainWindow", "Temperature", None))
        self.record_list.headerItem().setText(11, _translate("mainWindow", "Date", None))
        self.record_list.headerItem().setText(12, _translate("mainWindow", "Comments", None))
        self.pushButton_clear_records.setText(_translate("mainWindow", "Clear All Records", None))
        self.pushButton_save_button.setText(_translate("mainWindow", "Save Records", None))
        self.delete_record_button.setText(_translate("mainWindow", "Delete Record", None))
        self.pushButton_start.setText(_translate("mainWindow", "Run", None))
        self.button_openCloseSerial.setText(_translate("mainWindow", "Open connection", None))
        self.pushButton_apply_all_settings.setText(_translate("mainWindow", "Apply all Settings", None))
        self.groupBox_7.setTitle(_translate("mainWindow", "Monitoring modes", None))
        self.radioButton_air_fuel_SLPM.setText(_translate("mainWindow", "Air/Fuel SLPM", None))
        self.radioButton_massflow.setText(_translate("mainWindow", "Massflow - phi", None))
        self.radioButton_re_phi.setText(_translate("mainWindow", "Re - phi", None))
        self.label_42.setText(_translate("mainWindow", "air SLPM", None))
        self.label_44.setText(_translate("mainWindow", "fuel SLPM", None))

