# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alicat_control_ui.ui'
#
# Created: Mon Jul 22 09:53:55 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(940, 621)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_7 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 10, 391, 51))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.radioButton_air_fuel_SLPM = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_air_fuel_SLPM.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.radioButton_air_fuel_SLPM.setCheckable(True)
        self.radioButton_air_fuel_SLPM.setChecked(False)
        self.radioButton_air_fuel_SLPM.setObjectName(_fromUtf8("radioButton_air_fuel_SLPM"))
        self.radioButton_massflow = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_massflow.setGeometry(QtCore.QRect(270, 20, 111, 17))
        self.radioButton_massflow.setObjectName(_fromUtf8("radioButton_massflow"))
        self.radioButton_re_phi = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_re_phi.setGeometry(QtCore.QRect(180, 20, 81, 17))
        self.radioButton_re_phi.setChecked(False)
        self.radioButton_re_phi.setAutoExclusive(True)
        self.radioButton_re_phi.setObjectName(_fromUtf8("radioButton_re_phi"))
        self.radioButton_air_fuel_SLPM_2 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_air_fuel_SLPM_2.setGeometry(QtCore.QRect(100, 20, 71, 17))
        self.radioButton_air_fuel_SLPM_2.setCheckable(True)
        self.radioButton_air_fuel_SLPM_2.setChecked(True)
        self.radioButton_air_fuel_SLPM_2.setObjectName(_fromUtf8("radioButton_air_fuel_SLPM_2"))
        self.record_list = QtGui.QTreeWidget(self.centralwidget)
        self.record_list.setGeometry(QtCore.QRect(430, 10, 501, 231))
        self.record_list.setObjectName(_fromUtf8("record_list"))
        self.record_list.header().setVisible(True)
        self.record_list.header().setCascadingSectionResizes(False)
        self.record_list.header().setMinimumSectionSize(28)
        self.record_list.header().setSortIndicatorShown(False)
        self.record_list.header().setStretchLastSection(True)
        self.delete_record_button = QtGui.QPushButton(self.centralwidget)
        self.delete_record_button.setGeometry(QtCore.QRect(430, 250, 81, 23))
        self.delete_record_button.setObjectName(_fromUtf8("delete_record_button"))
        self.pushButton_save_button = QtGui.QPushButton(self.centralwidget)
        self.pushButton_save_button.setGeometry(QtCore.QRect(740, 250, 81, 23))
        self.pushButton_save_button.setObjectName(_fromUtf8("pushButton_save_button"))
        self.pushButton_clear_records = QtGui.QPushButton(self.centralwidget)
        self.pushButton_clear_records.setGeometry(QtCore.QRect(830, 250, 101, 23))
        self.pushButton_clear_records.setObjectName(_fromUtf8("pushButton_clear_records"))
        self.comments_textBox = QtGui.QTextEdit(self.centralwidget)
        self.comments_textBox.setGeometry(QtCore.QRect(700, 290, 231, 51))
        self.comments_textBox.setObjectName(_fromUtf8("comments_textBox"))
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(640, 290, 51, 51))
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.button_new_record_set = QtGui.QPushButton(self.centralwidget)
        self.button_new_record_set.setGeometry(QtCore.QRect(530, 290, 91, 51))
        self.button_new_record_set.setObjectName(_fromUtf8("button_new_record_set"))
        self.button_record_set = QtGui.QPushButton(self.centralwidget)
        self.button_record_set.setEnabled(False)
        self.button_record_set.setGeometry(QtCore.QRect(430, 290, 91, 51))
        self.button_record_set.setObjectName(_fromUtf8("button_record_set"))
        self.lcd_mean_velocity = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_mean_velocity.setGeometry(QtCore.QRect(770, 360, 101, 41))
        self.lcd_mean_velocity.setObjectName(_fromUtf8("lcd_mean_velocity"))
        self.lcd_temperature_Air = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_temperature_Air.setGeometry(QtCore.QRect(540, 410, 101, 41))
        self.lcd_temperature_Air.setAutoFillBackground(False)
        self.lcd_temperature_Air.setSmallDecimalPoint(False)
        self.lcd_temperature_Air.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_temperature_Air.setObjectName(_fromUtf8("lcd_temperature_Air"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 360, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(670, 410, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_45 = QtGui.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(880, 410, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.lcd_power = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_power.setGeometry(QtCore.QRect(770, 410, 101, 41))
        self.lcd_power.setObjectName(_fromUtf8("lcd_power"))
        self.label_43 = QtGui.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(877, 360, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 420, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(640, 360, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lcd_pressure_Air = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_pressure_Air.setGeometry(QtCore.QRect(540, 360, 101, 41))
        self.lcd_pressure_Air.setAutoFillBackground(False)
        self.lcd_pressure_Air.setSmallDecimalPoint(False)
        self.lcd_pressure_Air.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_pressure_Air.setObjectName(_fromUtf8("lcd_pressure_Air"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(430, 340, 491, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(430, 450, 501, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(430, 560, 501, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(410, 10, 21, 591))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(430, 570, 501, 31))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonNewSetup = QtGui.QPushButton(self.widget)
        self.buttonNewSetup.setObjectName(_fromUtf8("buttonNewSetup"))
        self.horizontalLayout.addWidget(self.buttonNewSetup)
        self.buttonLoadSetup = QtGui.QPushButton(self.widget)
        self.buttonLoadSetup.setObjectName(_fromUtf8("buttonLoadSetup"))
        self.horizontalLayout.addWidget(self.buttonLoadSetup)
        self.buttonRunAbort = QtGui.QPushButton(self.widget)
        self.buttonRunAbort.setObjectName(_fromUtf8("buttonRunAbort"))
        self.horizontalLayout.addWidget(self.buttonRunAbort)
        self.buttonReset = QtGui.QPushButton(self.widget)
        self.buttonReset.setObjectName(_fromUtf8("buttonReset"))
        self.horizontalLayout.addWidget(self.buttonReset)
        self.buttonSettings = QtGui.QPushButton(self.widget)
        self.buttonSettings.setObjectName(_fromUtf8("buttonSettings"))
        self.horizontalLayout.addWidget(self.buttonSettings)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Monitoring modes", None))
        self.radioButton_air_fuel_SLPM.setText(_translate("MainWindow", "Volume flow", None))
        self.radioButton_massflow.setText(_translate("MainWindow", "Massflow - fraction", None))
        self.radioButton_re_phi.setText(_translate("MainWindow", "Re - fraction", None))
        self.radioButton_air_fuel_SLPM_2.setText(_translate("MainWindow", "Mass flow", None))
        self.record_list.headerItem().setText(0, _translate("MainWindow", "Record #", None))
        self.record_list.headerItem().setText(1, _translate("MainWindow", "Record set", None))
        self.record_list.headerItem().setText(2, _translate("MainWindow", "Re", None))
        self.record_list.headerItem().setText(3, _translate("MainWindow", "phi", None))
        self.record_list.headerItem().setText(4, _translate("MainWindow", "TotalSLPM", None))
        self.record_list.headerItem().setText(5, _translate("MainWindow", "AirSLPM", None))
        self.record_list.headerItem().setText(6, _translate("MainWindow", "FuelSLPM", None))
        self.record_list.headerItem().setText(7, _translate("MainWindow", "Power", None))
        self.record_list.headerItem().setText(8, _translate("MainWindow", "U_mean", None))
        self.record_list.headerItem().setText(9, _translate("MainWindow", "Pressure", None))
        self.record_list.headerItem().setText(10, _translate("MainWindow", "Temperature", None))
        self.record_list.headerItem().setText(11, _translate("MainWindow", "Date", None))
        self.record_list.headerItem().setText(12, _translate("MainWindow", "Comments", None))
        self.delete_record_button.setText(_translate("MainWindow", "Delete Record", None))
        self.pushButton_save_button.setText(_translate("MainWindow", "Save Records", None))
        self.pushButton_clear_records.setText(_translate("MainWindow", "Clear All Records", None))
        self.label_36.setText(_translate("MainWindow", "Comments", None))
        self.button_new_record_set.setText(_translate("MainWindow", "new record set", None))
        self.button_record_set.setText(_translate("MainWindow", "record point", None))
        self.label.setText(_translate("MainWindow", "PSIA", None))
        self.label_17.setText(_translate("MainWindow", "Power", None))
        self.label_45.setText(_translate("MainWindow", "W", None))
        self.label_43.setText(_translate("MainWindow", "m/s", None))
        self.label_2.setText(_translate("MainWindow", "Temperature", None))
        self.label_16.setText(_translate("MainWindow", "Mean Velocity", None))
        self.buttonNewSetup.setText(_translate("MainWindow", "New Setup", None))
        self.buttonLoadSetup.setText(_translate("MainWindow", "Load Setup", None))
        self.buttonRunAbort.setText(_translate("MainWindow", "Run/Abort", None))
        self.buttonReset.setText(_translate("MainWindow", "Reset", None))
        self.buttonSettings.setText(_translate("MainWindow", "Settings", None))

