# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_setup_ui.ui'
#
# Created: Mon Jul 22 16:31:30 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NewSetupWindow(object):
    def setupUi(self, NewSetupWindow):
        NewSetupWindow.setObjectName(_fromUtf8("NewSetupWindow"))
        NewSetupWindow.resize(720, 441)
        self.tabWidget = QtGui.QTabWidget(NewSetupWindow)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 701, 381))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_burnerGeom = QtGui.QWidget()
        self.tab_burnerGeom.setObjectName(_fromUtf8("tab_burnerGeom"))
        self.rButtonHoles = QtGui.QRadioButton(self.tab_burnerGeom)
        self.rButtonHoles.setGeometry(QtCore.QRect(40, 70, 82, 17))
        self.rButtonHoles.setChecked(True)
        self.rButtonHoles.setObjectName(_fromUtf8("rButtonHoles"))
        self.rButtonSlits = QtGui.QRadioButton(self.tab_burnerGeom)
        self.rButtonSlits.setGeometry(QtCore.QRect(40, 100, 82, 17))
        self.rButtonSlits.setObjectName(_fromUtf8("rButtonSlits"))
        self.inputGeometryA = QtGui.QLineEdit(self.tab_burnerGeom)
        self.inputGeometryA.setGeometry(QtCore.QRect(210, 70, 51, 20))
        self.inputGeometryA.setText(_fromUtf8(""))
        self.inputGeometryA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputGeometryA.setObjectName(_fromUtf8("inputGeometryA"))
        self.inputGeometryB = QtGui.QLineEdit(self.tab_burnerGeom)
        self.inputGeometryB.setEnabled(False)
        self.inputGeometryB.setGeometry(QtCore.QRect(210, 100, 51, 20))
        self.inputGeometryB.setText(_fromUtf8(""))
        self.inputGeometryB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputGeometryB.setObjectName(_fromUtf8("inputGeometryB"))
        self.inputGeometryNumber = QtGui.QLineEdit(self.tab_burnerGeom)
        self.inputGeometryNumber.setEnabled(True)
        self.inputGeometryNumber.setGeometry(QtCore.QRect(210, 220, 51, 20))
        self.inputGeometryNumber.setText(_fromUtf8(""))
        self.inputGeometryNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputGeometryNumber.setObjectName(_fromUtf8("inputGeometryNumber"))
        self.label_5 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_5.setGeometry(QtCore.QRect(180, 70, 21, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_6.setGeometry(QtCore.QRect(180, 100, 21, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_20 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_20.setGeometry(QtCore.QRect(110, 220, 91, 21))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_21.setGeometry(QtCore.QRect(270, 70, 21, 21))
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_22.setGeometry(QtCore.QRect(270, 100, 21, 21))
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.rButtonOther = QtGui.QRadioButton(self.tab_burnerGeom)
        self.rButtonOther.setGeometry(QtCore.QRect(40, 130, 82, 17))
        self.rButtonOther.setObjectName(_fromUtf8("rButtonOther"))
        self.inputGeometryL = QtGui.QLineEdit(self.tab_burnerGeom)
        self.inputGeometryL.setEnabled(False)
        self.inputGeometryL.setGeometry(QtCore.QRect(210, 190, 51, 20))
        self.inputGeometryL.setText(_fromUtf8(""))
        self.inputGeometryL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputGeometryL.setObjectName(_fromUtf8("inputGeometryL"))
        self.label_7 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_7.setGeometry(QtCore.QRect(180, 190, 21, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_23 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_23.setGeometry(QtCore.QRect(270, 190, 21, 21))
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_24.setGeometry(QtCore.QRect(310, 250, 31, 21))
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_8 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_8.setGeometry(QtCore.QRect(160, 250, 41, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.inputGeometryTotal = QtGui.QLineEdit(self.tab_burnerGeom)
        self.inputGeometryTotal.setEnabled(False)
        self.inputGeometryTotal.setGeometry(QtCore.QRect(210, 250, 91, 20))
        self.inputGeometryTotal.setText(_fromUtf8(""))
        self.inputGeometryTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputGeometryTotal.setObjectName(_fromUtf8("inputGeometryTotal"))
        self.label_9 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_9.setGeometry(QtCore.QRect(160, 130, 41, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.inputGeometryArea = QtGui.QLineEdit(self.tab_burnerGeom)
        self.inputGeometryArea.setEnabled(False)
        self.inputGeometryArea.setGeometry(QtCore.QRect(210, 130, 91, 20))
        self.inputGeometryArea.setText(_fromUtf8(""))
        self.inputGeometryArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputGeometryArea.setObjectName(_fromUtf8("inputGeometryArea"))
        self.label_33 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_33.setGeometry(QtCore.QRect(310, 130, 31, 21))
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_10 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_10.setGeometry(QtCore.QRect(120, 160, 81, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_34 = QtGui.QLabel(self.tab_burnerGeom)
        self.label_34.setGeometry(QtCore.QRect(310, 160, 31, 21))
        self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.inputGeometryPerimeter = QtGui.QLineEdit(self.tab_burnerGeom)
        self.inputGeometryPerimeter.setEnabled(False)
        self.inputGeometryPerimeter.setGeometry(QtCore.QRect(210, 160, 91, 20))
        self.inputGeometryPerimeter.setText(_fromUtf8(""))
        self.inputGeometryPerimeter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputGeometryPerimeter.setObjectName(_fromUtf8("inputGeometryPerimeter"))
        self.tabWidget.addTab(self.tab_burnerGeom, _fromUtf8(""))
        self.tab_gas = QtGui.QWidget()
        self.tab_gas.setEnabled(True)
        self.tab_gas.setObjectName(_fromUtf8("tab_gas"))
        self.groupBox = QtGui.QGroupBox(self.tab_gas)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 291, 321))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(80, 50, 21, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.inputMaxCapacity = QtGui.QLineEdit(self.groupBox)
        self.inputMaxCapacity.setGeometry(QtCore.QRect(110, 80, 61, 20))
        self.inputMaxCapacity.setText(_fromUtf8(""))
        self.inputMaxCapacity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputMaxCapacity.setObjectName(_fromUtf8("inputMaxCapacity"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(50, 20, 51, 21))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(30, 80, 71, 21))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_32 = QtGui.QLabel(self.groupBox)
        self.label_32.setGeometry(QtCore.QRect(180, 80, 51, 21))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_35 = QtGui.QLabel(self.groupBox)
        self.label_35.setGeometry(QtCore.QRect(10, 260, 91, 21))
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.inputGasName = QtGui.QComboBox(self.groupBox)
        self.inputGasName.setGeometry(QtCore.QRect(110, 110, 91, 22))
        self.inputGasName.setObjectName(_fromUtf8("inputGasName"))
        self.inputFuelHHF = QtGui.QLineEdit(self.groupBox)
        self.inputFuelHHF.setEnabled(False)
        self.inputFuelHHF.setGeometry(QtCore.QRect(112, 170, 91, 20))
        self.inputFuelHHF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputFuelHHF.setObjectName(_fromUtf8("inputFuelHHF"))
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(50, 110, 46, 21))
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.inputAirFuelRatio = QtGui.QLineEdit(self.groupBox)
        self.inputAirFuelRatio.setEnabled(False)
        self.inputAirFuelRatio.setGeometry(QtCore.QRect(112, 140, 91, 20))
        self.inputAirFuelRatio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputAirFuelRatio.setObjectName(_fromUtf8("inputAirFuelRatio"))
        self.label_31 = QtGui.QLabel(self.groupBox)
        self.label_31.setGeometry(QtCore.QRect(210, 200, 81, 21))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_28 = QtGui.QLabel(self.groupBox)
        self.label_28.setGeometry(QtCore.QRect(210, 170, 46, 21))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_46 = QtGui.QLabel(self.groupBox)
        self.label_46.setGeometry(QtCore.QRect(210, 110, 21, 21))
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(80, 140, 21, 21))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.inputGasViscosity = QtGui.QLineEdit(self.groupBox)
        self.inputGasViscosity.setEnabled(False)
        self.inputGasViscosity.setGeometry(QtCore.QRect(112, 230, 91, 20))
        self.inputGasViscosity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputGasViscosity.setObjectName(_fromUtf8("inputGasViscosity"))
        self.label_29 = QtGui.QLabel(self.groupBox)
        self.label_29.setGeometry(QtCore.QRect(30, 230, 71, 21))
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_41 = QtGui.QLabel(self.groupBox)
        self.label_41.setGeometry(QtCore.QRect(210, 260, 46, 21))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.inputGasMolecularWeight = QtGui.QLineEdit(self.groupBox)
        self.inputGasMolecularWeight.setEnabled(False)
        self.inputGasMolecularWeight.setGeometry(QtCore.QRect(112, 260, 91, 20))
        self.inputGasMolecularWeight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputGasMolecularWeight.setObjectName(_fromUtf8("inputGasMolecularWeight"))
        self.label_27 = QtGui.QLabel(self.groupBox)
        self.label_27.setGeometry(QtCore.QRect(70, 170, 31, 21))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.inputGasDensity = QtGui.QLineEdit(self.groupBox)
        self.inputGasDensity.setEnabled(False)
        self.inputGasDensity.setGeometry(QtCore.QRect(112, 200, 91, 20))
        self.inputGasDensity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputGasDensity.setObjectName(_fromUtf8("inputGasDensity"))
        self.label_39 = QtGui.QLabel(self.groupBox)
        self.label_39.setGeometry(QtCore.QRect(210, 230, 71, 21))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.inputGasID = QtGui.QLineEdit(self.groupBox)
        self.inputGasID.setEnabled(False)
        self.inputGasID.setGeometry(QtCore.QRect(240, 110, 31, 20))
        self.inputGasID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputGasID.setObjectName(_fromUtf8("inputGasID"))
        self.label_30 = QtGui.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(60, 200, 41, 21))
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.inputSerialPort = QtGui.QComboBox(self.groupBox)
        self.inputSerialPort.setGeometry(QtCore.QRect(110, 20, 69, 22))
        self.inputSerialPort.setObjectName(_fromUtf8("inputSerialPort"))
        self.inputSerialPort.addItem(_fromUtf8(""))
        self.inputSerialPort.addItem(_fromUtf8(""))
        self.inputSerialPort.addItem(_fromUtf8(""))
        self.inputSerialPort.addItem(_fromUtf8(""))
        self.inputSerialPort.addItem(_fromUtf8(""))
        self.inputSerialPort.addItem(_fromUtf8(""))
        self.inputSerialPort.addItem(_fromUtf8(""))
        self.inputSerialPort.addItem(_fromUtf8(""))
        self.inputSerialPort.addItem(_fromUtf8(""))
        self.inputFlowmeterID = QtGui.QComboBox(self.groupBox)
        self.inputFlowmeterID.setGeometry(QtCore.QRect(110, 50, 69, 22))
        self.inputFlowmeterID.setObjectName(_fromUtf8("inputFlowmeterID"))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.inputFlowmeterID.addItem(_fromUtf8(""))
        self.buttonAddFlowmeter = QtGui.QPushButton(self.tab_gas)
        self.buttonAddFlowmeter.setGeometry(QtCore.QRect(320, 30, 41, 121))
        self.buttonAddFlowmeter.setObjectName(_fromUtf8("buttonAddFlowmeter"))
        self.buttonRemoveFlowmeter = QtGui.QPushButton(self.tab_gas)
        self.buttonRemoveFlowmeter.setGeometry(QtCore.QRect(320, 300, 41, 41))
        self.buttonRemoveFlowmeter.setObjectName(_fromUtf8("buttonRemoveFlowmeter"))
        self.treeViewFlowmeters = QtGui.QTreeWidget(self.tab_gas)
        self.treeViewFlowmeters.setGeometry(QtCore.QRect(370, 30, 321, 311))
        self.treeViewFlowmeters.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeViewFlowmeters.setObjectName(_fromUtf8("treeViewFlowmeters"))
        self.treeViewFlowmeters.header().setDefaultSectionSize(70)
        self.buttonMixFlowmeter = QtGui.QPushButton(self.tab_gas)
        self.buttonMixFlowmeter.setGeometry(QtCore.QRect(320, 250, 41, 41))
        self.buttonMixFlowmeter.setObjectName(_fromUtf8("buttonMixFlowmeter"))
        self.tabWidget.addTab(self.tab_gas, _fromUtf8(""))
        self.buttonCreate = QtGui.QPushButton(NewSetupWindow)
        self.buttonCreate.setGeometry(QtCore.QRect(550, 400, 75, 23))
        self.buttonCreate.setObjectName(_fromUtf8("buttonCreate"))
        self.buttonCancel = QtGui.QPushButton(NewSetupWindow)
        self.buttonCancel.setGeometry(QtCore.QRect(630, 400, 75, 23))
        self.buttonCancel.setObjectName(_fromUtf8("buttonCancel"))

        self.retranslateUi(NewSetupWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(NewSetupWindow)

    def retranslateUi(self, NewSetupWindow):
        NewSetupWindow.setWindowTitle(_translate("NewSetupWindow", "Dialog", None))
        self.rButtonHoles.setText(_translate("NewSetupWindow", "Holes", None))
        self.rButtonSlits.setText(_translate("NewSetupWindow", "Slits", None))
        self.label_5.setText(_translate("NewSetupWindow", "a", None))
        self.label_6.setText(_translate("NewSetupWindow", "b", None))
        self.label_20.setText(_translate("NewSetupWindow", "# of holes/slits", None))
        self.label_21.setText(_translate("NewSetupWindow", "mm", None))
        self.label_22.setText(_translate("NewSetupWindow", "mm", None))
        self.rButtonOther.setText(_translate("NewSetupWindow", "Other", None))
        self.label_7.setText(_translate("NewSetupWindow", "L", None))
        self.label_23.setText(_translate("NewSetupWindow", "mm", None))
        self.label_24.setText(_translate("NewSetupWindow", "mm^2", None))
        self.label_8.setText(_translate("NewSetupWindow", "A_total", None))
        self.label_9.setText(_translate("NewSetupWindow", "A_hole", None))
        self.label_33.setText(_translate("NewSetupWindow", "mm^2", None))
        self.label_10.setText(_translate("NewSetupWindow", "Perimeter_hole", None))
        self.label_34.setText(_translate("NewSetupWindow", "mm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_burnerGeom), _translate("NewSetupWindow", "Burner Geometry", None))
        self.groupBox.setTitle(_translate("NewSetupWindow", "Flowmeter", None))
        self.label_14.setText(_translate("NewSetupWindow", "ID", None))
        self.label_15.setText(_translate("NewSetupWindow", "Serial Port", None))
        self.label_16.setText(_translate("NewSetupWindow", "Max. capacity", None))
        self.label_32.setText(_translate("NewSetupWindow", "SLPM", None))
        self.label_35.setText(_translate("NewSetupWindow", "molecular weight", None))
        self.inputFuelHHF.setText(_translate("NewSetupWindow", "-", None))
        self.inputFuelHHF.setPlaceholderText(_translate("NewSetupWindow", "0", None))
        self.label_25.setText(_translate("NewSetupWindow", "Gas", None))
        self.inputAirFuelRatio.setText(_translate("NewSetupWindow", "-", None))
        self.inputAirFuelRatio.setPlaceholderText(_translate("NewSetupWindow", "0", None))
        self.label_31.setText(_translate("NewSetupWindow", "Kg/m3  @ 25ºC", None))
        self.label_28.setText(_translate("NewSetupWindow", "MJ/Kg", None))
        self.label_46.setText(_translate("NewSetupWindow", "ID", None))
        self.label_26.setText(_translate("NewSetupWindow", "A/F", None))
        self.inputGasViscosity.setText(_translate("NewSetupWindow", "-", None))
        self.inputGasViscosity.setPlaceholderText(_translate("NewSetupWindow", "0", None))
        self.label_29.setText(_translate("NewSetupWindow", "din. viscosity", None))
        self.label_41.setText(_translate("NewSetupWindow", "Kg/Kmol", None))
        self.inputGasMolecularWeight.setText(_translate("NewSetupWindow", "-", None))
        self.inputGasMolecularWeight.setPlaceholderText(_translate("NewSetupWindow", "0", None))
        self.label_27.setText(_translate("NewSetupWindow", "HHF", None))
        self.inputGasDensity.setText(_translate("NewSetupWindow", "-", None))
        self.inputGasDensity.setPlaceholderText(_translate("NewSetupWindow", "0", None))
        self.label_39.setText(_translate("NewSetupWindow", "Kg/ms  @ 25ºC", None))
        self.inputGasID.setText(_translate("NewSetupWindow", "-", None))
        self.label_30.setText(_translate("NewSetupWindow", "density", None))
        self.inputSerialPort.setItemText(0, _translate("NewSetupWindow", "COM1", None))
        self.inputSerialPort.setItemText(1, _translate("NewSetupWindow", "COM2", None))
        self.inputSerialPort.setItemText(2, _translate("NewSetupWindow", "COM3", None))
        self.inputSerialPort.setItemText(3, _translate("NewSetupWindow", "COM4", None))
        self.inputSerialPort.setItemText(4, _translate("NewSetupWindow", "COM4", None))
        self.inputSerialPort.setItemText(5, _translate("NewSetupWindow", "COM5", None))
        self.inputSerialPort.setItemText(6, _translate("NewSetupWindow", "COM6", None))
        self.inputSerialPort.setItemText(7, _translate("NewSetupWindow", "COM7", None))
        self.inputSerialPort.setItemText(8, _translate("NewSetupWindow", "COM8", None))
        self.inputFlowmeterID.setItemText(0, _translate("NewSetupWindow", "A", None))
        self.inputFlowmeterID.setItemText(1, _translate("NewSetupWindow", "B", None))
        self.inputFlowmeterID.setItemText(2, _translate("NewSetupWindow", "C", None))
        self.inputFlowmeterID.setItemText(3, _translate("NewSetupWindow", "D", None))
        self.inputFlowmeterID.setItemText(4, _translate("NewSetupWindow", "E", None))
        self.inputFlowmeterID.setItemText(5, _translate("NewSetupWindow", "F", None))
        self.inputFlowmeterID.setItemText(6, _translate("NewSetupWindow", "G", None))
        self.inputFlowmeterID.setItemText(7, _translate("NewSetupWindow", "H", None))
        self.inputFlowmeterID.setItemText(8, _translate("NewSetupWindow", "I", None))
        self.inputFlowmeterID.setItemText(9, _translate("NewSetupWindow", "J", None))
        self.inputFlowmeterID.setItemText(10, _translate("NewSetupWindow", "K", None))
        self.inputFlowmeterID.setItemText(11, _translate("NewSetupWindow", "L", None))
        self.inputFlowmeterID.setItemText(12, _translate("NewSetupWindow", "M", None))
        self.inputFlowmeterID.setItemText(13, _translate("NewSetupWindow", "N", None))
        self.inputFlowmeterID.setItemText(14, _translate("NewSetupWindow", "O", None))
        self.inputFlowmeterID.setItemText(15, _translate("NewSetupWindow", "P", None))
        self.inputFlowmeterID.setItemText(16, _translate("NewSetupWindow", "Q", None))
        self.inputFlowmeterID.setItemText(17, _translate("NewSetupWindow", "R", None))
        self.inputFlowmeterID.setItemText(18, _translate("NewSetupWindow", "S", None))
        self.inputFlowmeterID.setItemText(19, _translate("NewSetupWindow", "T", None))
        self.inputFlowmeterID.setItemText(20, _translate("NewSetupWindow", "U", None))
        self.inputFlowmeterID.setItemText(21, _translate("NewSetupWindow", "V", None))
        self.inputFlowmeterID.setItemText(22, _translate("NewSetupWindow", "W", None))
        self.inputFlowmeterID.setItemText(23, _translate("NewSetupWindow", "X", None))
        self.inputFlowmeterID.setItemText(24, _translate("NewSetupWindow", "Y", None))
        self.inputFlowmeterID.setItemText(25, _translate("NewSetupWindow", "Z", None))
        self.buttonAddFlowmeter.setText(_translate("NewSetupWindow", ">", None))
        self.buttonRemoveFlowmeter.setText(_translate("NewSetupWindow", "X", None))
        self.treeViewFlowmeters.headerItem().setText(0, _translate("NewSetupWindow", "ID", None))
        self.treeViewFlowmeters.headerItem().setText(1, _translate("NewSetupWindow", "Gas", None))
        self.treeViewFlowmeters.headerItem().setText(2, _translate("NewSetupWindow", "GasID", None))
        self.treeViewFlowmeters.headerItem().setText(3, _translate("NewSetupWindow", "Capacity", None))
        self.treeViewFlowmeters.headerItem().setText(4, _translate("NewSetupWindow", "Port", None))
        self.buttonMixFlowmeter.setText(_translate("NewSetupWindow", "MIX", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gas), _translate("NewSetupWindow", "Flowmeter", None))
        self.buttonCreate.setText(_translate("NewSetupWindow", "Create", None))
        self.buttonCancel.setText(_translate("NewSetupWindow", "Cancel", None))

